### ISSUE TITLE
不要なentity/repository削除 / サーバー

### ISSUE THREAD

**Issue by Daaaai0809** [saitamau-maximum/meline#63]

**Comment by sor4chi** [comment]
ChannelToChannels,MessageToMessages

**Comment by sor4chi** [comment]
そもそもMessageToMessageRepositoryとChannelToChannelRepositoryもいらなさそう

**Comment by sor4chi** [comment]
中間テーブルと本テーブルが別リポジトリになってるからlockがリポジトリ跨ぐときに一度解除されてて意味なくなってしまってる
